[versions]
agp = "8.13.1"
activity = "1.8.0"
constraintlayout = "2.1.4"
assertjCoreVersion = "3.27.6"
coreTesting = "2.2.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
junitTest = "1.3.0"
lombock = "1.18.42"
roomRuntime = "2.8.3"
guava = "33.5.0-jre"
runner = "1.7.0"
worker = "2.11.0"

[libraries]
androidx-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitTest" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
androidx-rules = { module = "androidx.test:rules", version.ref = "runner" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lombock = { group = "org.projectlombok", name = "lombok", version.ref = "lombock" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
worker = { module = "androidx.work:work-runtime", version.ref = "worker" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

